### ISSUE TITLE
Add capability in vent to convert fields from hexadecimal values to string before entering into the database

### ISSUE THREAD

**Issue by compleatang** [monax/bosmarmot#155]
A lot of fields in the blockchain are bytes32 which means they're stored in their hexadecimal representation. Before entering them into the database, these need to be converted back to their string form.

Solution: Add an additional attribute `"hexToString": true|false` to the column declaration in the sqlsol JSON config. Fields that are marked as 'true' should be converted from hex to string before the value is inserted into the DB.

Migrated from AN-559

**Comment by hiturria** [comment]
There is already a way to solve this, an attribute `"bytesToString": true|false` has been created in the sqlsol JSON config.
```
"Columns"  : {
      "key" : {"name" : "testkey", "type": "bytes32", "primary" : true},
      "name" : {"name" : "testname", "type": "bytes32", "primary" : true, "bytesToString": true},
      "description": {"name" : "testdescription", "type": "bytes32", "primary" : false}
    }
```
this way, fields with that attribute marked as 'true' are being converted to string and after that, inserted in the DB.
Fixed in #157
