### ISSUE TITLE
Error: Address not provided to call

### ISSUE THREAD

**Issue by painpunisher** [monax/bosmarmot#160]
Hey mate,

first i just want to thank for your awesome tutorial.

I wanted to start the chain with another contract but i encountered this problem.
`Error: Address not provided to call
    at /home/atlinux16/testo_burrow/bosmarmot/example/basic-app/node_modules/@monax/burrow/lib/contracts/function.js:110:45
    at new Promise (<anonymous>)
    at Contract.call (/home/atlinux16/testo_burrow/bosmarmot/example/basic-app/node_modules/@monax/burrow/lib/contracts/function.js:107:13)
    at param.then.then.newvar (/home/atlinux16/testo_burrow/bosmarmot/example/basic-app/app.js:71:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

i hope you can help me.

The simplestorage worked without problem.

Thank you very much.

**Comment by dennismckinnon** [comment]
Hello,

After looking through it I suspect that the issue might be in the deploy.output.json and/or the value being retrieved from it.

Can you confirm for me that the address of your contract appears under simple storage, or if you changed the name and it appears under a new name that you have changed the line https://github.com/monax/bosmarmot/blob/develop/example/basic-app/app.js#L29
to properly reflect the new name?

If all that is working fine, can you provide extra details as to how you got this to break? file renaming, new solidity etc. its possible that if the changes you made failed to compile that the entry might be missing.

Thanks!

**Comment by compleatang** [comment]
closing as unanswered. feel free to reopen if the issue persists.
