### ISSUE TITLE
Vent should move the loaders functions out of the Consumer function

### ISSUE THREAD

**Issue by compleatang** [monax/bosmarmot#164]
The consuner function is a bit of a monolith and could do with some trimming. In particular, we should consider moving the loading functions out of `Consumer`. This would allow using libraries of go code to programmicially build their structs and just give the struct to the `Consumer` rather than forcing them to write a file solely for Vent to consume it.

**Comment by compleatang** [comment]
Same for ABIs

**Comment by hiturria** [comment]
That has been refactored in #166 for both spec & abi loaders.
