### ISSUE TITLE
Vent to be able to save raw and block and transaction data

### ISSUE THREAD

**Issue by compleatang** [monax/bosmarmot#165]
Vent has all the framework to be a great base that can send structured infromation necessary to build block explorers. While it is currently focused on filtering based on solidity events, we have most of the necessary code to extend vent and boot it in a mode which will allow us to save *all* block and transaction data. Then we can enable easy configuration for open sourced block explorers for burrow chains. Note, I would think this would be mutually exclusive with running a single vent instance in "filter" mode(the current configuration)

I'd envision a scenario where we utilize two tables: `blocks` and `transactions`.

The `blocks` table would save all of the block header information, have `height` and `hash` as primary keys. The `transaction` table would save all of the available transaction information (e.g., `type`, `from`, `to`, `data`, `blockHeight`) and have `hash` as primary keys.

**Comment by hiturria** [comment]
This has been addressed in #171 and #172 .
A new boolean `--db-block` flag has been added & when set to `true`, block and transaction tables are created (as well as event tables) & all block and transaction data is persisted.
When set to `false` just event tables are created.
