### ISSUE TITLE
Extend Vent capability to load multiple Tables.spec files and consolidate

### ISSUE THREAD

**Issue by j-h-scheufen** [monax/bosmarmot#185]
Currently, Vent loads all configuration information from a single file. It should be possible to distribute Vent configurations across multiple *.spec files and have vent load and combine these. The reason for this is to support modularity, e.g. a project that uses the Blackstone framework (which comes with its own Tables.spec) and builds additional capabilities on top of it and needs to add additional (application-specific) tables to Vent. This is currently not possible, instead each project must find a way to add their custom tables to the Blackstone .spec file.

A decision needs to be made how to deal with conflicting / redundant declarations of tables, i.e. if it should be possible to overload prior declarations. For this to happen, Vent would have to first collect all spec files and then handle duplicate declarations. It therefore seems more straight-forward for now to disallow overloading and throw an error / issue a warning if duplicate declarations are encountered.

**Comment by silasdavis** [comment]
This is currently supported by `burrow vent`
