### ISSUE TITLE
I am not found example use burrow.query.*

### ISSUE THREAD

**Issue by AlexStormV** [monax/bosmarmot#186]
Please, add simple example  use "burrow.query.*" in the  "burrow.js/README.md"

I tried it like this:

function list(){
    let listAccounts = burrow.query.ListAccounts("balance > 1000.0", function(error, data){
            console.log(error)
            console.log(data)
        }
    );
    console.log(    listAccounts)
}

it is not working :(

**Comment by AlexStormV** [comment]
I found error:  balance > Balance 

it is worked:

function list(){
    let listAccounts = burrow.query.ListAccounts("Balance > 1000.0", function(error, data){
            console.log(error)
            console.log(data)
        }
    );
    console.log(    listAccounts)
}


Please, add this simple example in the "burrow.js/README.md"

**Comment by dennismckinnon** [comment]
Thanks. I have included some documentation in the readme as of the latest version to explain the usage of ListAccounts query tags
