### ISSUE TITLE
burrow.executionEvents.GetTx throws error

### ISSUE THREAD

**Issue by ToniyaSundaram** [monax/bosmarmot#198]
I am running a single full node. I executed a CallTxSync and the transaction was successful. I tried to query the transaction details using burrow.executionEvents.GetTx method. But it throws 
`"Error: 2 UNKNOWN: transaction with hash 20744BBA297C0768C14D4B3BA46AF562F3216BCB not found in state"`

Is there any way I can debug this issue and fix it ? 

Example:
```
function getTxByHash(txHash){
  txHash = Buffer.from(txHash, 'hex')
  return new Promise(function(resolve, reject) {
    burrow.executionEvents.GetTx(
      { TxHash: txHash, Wait: false},
      (error, data) => {
        if (data) {
          resolve(data);
        } else {
          reject(error);
        }
      }
    );
  });
}
```

**Comment by seanyoung** [comment]
I think the call looks right. It looks very much like the transaction hash was used.
A more complete example would be helpful -- if this is still an issue would you please open a new issue on https://github.com/hyperledger/burrow  this is where the burrow js interface now lives.

**Comment by silasdavis** [comment]
Closing for now, please re-open in the Burrow repo if the issue persists with the latest versions
