### ISSUE TITLE
Compatibility issue with new Burrow build when building bos

### ISSUE THREAD

**Issue by smblucker** [monax/bosmarmot#2]
References/calls to NewBurrowKeyClient() in bosmarmot/monax/keys/keys.go and bosmarmot/monax/pkgs/jobs/jobs_contacts.go and jobs_transact.go no longer produce valid build/install results for bos; function name has been changed in hyperledger/burrow/keys/key_client.go to NewKeyClient(...).

**System Details**

Burrow Version: 0.16
Go Version: 1.9.3
Operation System: Ubuntu 16.04

**Expected Results**

Running `go get -u github.com/monax/bosmarmot/monax/cmd/bos` produces a valid executable without errors.

**Actual Results**

Running `go get -u github.com/monax/bosmarmot/monax/cmd/bos` produces the following error:

`github.com/monax/bosmarmot/monax/keys/keys.go:30:3: undefined: "github.com/hyperledger/burrow/keys".NewBurrowKeyClient`

**Reproduction**

In $GOPATH, run:

`go get -u github.com/hyperledger/burrow/cmd/burrow`
`cd $GOPATH/src/github.com/hyperledger/burrow`
`git checkout feature/hypermarmot`
`go install ./cmd/burrow`
`go get -u github.com/monax/bosmarmot/keys/cmd/monax-keys`
`go get -u github.com/monax/bosmarmot/monax/cmd/bos`

**Comment by silasdavis** [comment]
fixed by #3
