### ISSUE TITLE
Storage capacity and timelag in Monax chains

### ISSUE THREAD

**Issue by jerrinjames1107** [monax/bosmarmot#38]
I have a query regarding the _storage capacity_ of Monax.Is there any specific limit?.Am using monax version 0.17.0.

I also tried a simple **set** and **get** function.There was a time lag for both the functions.The time lag increased on successive usage of the function(The time lag reached about 90s after calling the function for about 40 times).Is there any solution for this issue?

**Comment by compleatang** [comment]
Please upgrade your burrow instance to >=0.18.0. There was a known issue in earlier versions of burrow which has been fixed.
